const BANK=QUESTION_BANK, companies=["TCS","Infosys","Wipro","Accenture","Cognizant","Capgemini","Deloitte","IBM","Amazon","Microsoft"];
let subject="All Subjects",difficulty="All Levels",company="All Companies",amount=10,questions=[],index=0,score=0,time=30,timer=null,answered=false;
let stats=JSON.parse(localStorage.getItem("qmCRTStats")||'{"attempts":0,"scores":[],"history":[],"strong":0}');
const $=s=>document.querySelector(s),all=()=>Object.values(BANK).flat(),shuffle=a=>[...a].sort(()=>Math.random()-.5);
function pool(){let p=all();if(subject!="All Subjects")p=p.filter(q=>q.subject==subject);if(difficulty!="All Levels")p=p.filter(q=>q.difficulty==difficulty);if(company!="All Companies")p=p.filter(q=>q.company==company);return p}
function info(){let p=pool();$("#match").textContent=`${p.length.toLocaleString()} matching questions available`;$("#bankTotal").textContent=`${all().length.toLocaleString()} questions`}
function start(){let p=pool();if(!p.length)return alert("No questions match these filters. Try another combination.");questions=shuffle(p).slice(0,Math.min(+amount,p.length));index=score=0;$("#practice").classList.add("hidden");$("#result").classList.add("hidden");$("#quiz").classList.remove("hidden");show();scrollTo(0,0)}
function show(){answered=false;time=30;clearInterval(timer);let q=questions[index];$("#qsubject").textContent=q.subject.toUpperCase();$("#qnum").textContent=`Question ${index+1} of ${questions.length}`;$("#bar").style.width=((index+1)/questions.length*100)+"%";$("#time").textContent=time;$("#qcompany").textContent=q.company+" style";$("#qlevel").textContent=q.difficulty;$("#qtopic").textContent=q.topic;$("#q").textContent=q.question;$("#options").innerHTML=q.options.map((x,i)=>`<button class="option" data-i="${i}">${String.fromCharCode(65+i)}. ${x}</button>`).join("");$("#feedback").className="feedback hidden";$("#next").classList.add("hidden");document.querySelectorAll(".option").forEach(b=>b.onclick=()=>answer(+b.dataset.i));timer=setInterval(()=>{time--;$("#time").textContent=time;if(time<=0){clearInterval(timer);answer(-1,true)}},1000)}
function answer(choice,timeout=false){if(answered)return;answered=true;clearInterval(timer);let q=questions[index],ok=choice===q.answer;if(ok)score++;document.querySelectorAll(".option").forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add("correct");if(i===choice&&!ok)b.classList.add("wrong")});let good=["Excellent! Keep that momentum going.","Correct — strong work.","Nice one! Your preparation is paying off."];let support=["No worries — this is practice, not a final result.","Good attempt. Review the explanation and keep going.","It’s okay to miss one. Learn the pattern and try the next.","Don’t let one question slow you down. Use the hint and continue.","Almost there. Every mistake is useful practice."];let msg=(ok?good: support)[Math.floor(Math.random()*(ok?good:support).length)];$("#feedback").className="feedback "+(ok?"success":"fail");$("#feedback").innerHTML=`<strong>${ok?"✓ "+msg:"💪 "+msg}</strong><div>${timeout?"Time ran out. ":""}Correct answer: <b>${q.options[q.answer]}</b><br>${q.explanation}<br><small>Hint: ${q.hint}</small></div>`;$("#next").textContent=index===questions.length-1?"View Result →":"Next Question →";$("#next").classList.remove("hidden")}
function next(){if(!answered)return;if(index<questions.length-1){index++;show()}else finish()}
function finish(){let acc=Math.round(score/questions.length*100);stats.attempts++;stats.scores.push(acc);if(acc>=70)stats.strong++;stats.history.unshift({s:subject,d:difficulty,c:company,score,total:questions.length,a:acc,date:new Date().toLocaleDateString()});stats.history=stats.history.slice(0,10);localStorage.setItem("qmCRTStats",JSON.stringify(stats));$("#quiz").classList.add("hidden");$("#result").classList.remove("hidden");$("#score").textContent=score;$("#total").textContent="/ "+questions.length;$("#correct").textContent=score;$("#wrong").textContent=questions.length-score;$("#accuracy").textContent=acc+"%";$("#best").textContent=Math.max(...stats.scores,0)+"%";$("#resultTitle").textContent=acc>=90?"Outstanding!":acc>=75?"Excellent progress!":acc>=60?"Good effort!":"Keep practicing!";$("#emoji").textContent=acc>=80?"🏆":acc>=60?"🌟":"💪";$("#resultText").textContent=acc>=70?"You are building strong placement-test habits. Try a harder level or another subject next.":"Every attempt is useful. Review the hints, learn from mistakes, and try another short test.";dash();$("#result").scrollIntoView({behavior:"smooth"})}
function dash(){let best=Math.max(...stats.scores,0),avg=stats.scores.length?Math.round(stats.scores.reduce((a,b)=>a+b,0)/stats.scores.length):0;$("#attempts").textContent=stats.attempts;$("#high").textContent=best+"%";$("#avg").textContent=avg+"%";$("#strong").textContent=stats.strong;$("#history").innerHTML=stats.history.length?stats.history.map(x=>`<div class="history"><b>${x.s}</b><span>${x.score}/${x.total} · ${x.a}% · ${x.d} · ${x.date}</span></div>`).join(""):"<p style='color:#697386'>Complete a test to build your history.</p>"}
companies.forEach(c=>$("#company").insertAdjacentHTML("beforeend",`<option>${c}</option>`));
$("#subject").onchange=e=>{subject=e.target.value;info()};$("#difficulty").onchange=e=>{difficulty=e.target.value;info()};$("#company").onchange=e=>{company=e.target.value;info()};$("#amount").onchange=e=>amount=e.target.value;
document.querySelectorAll(".quick button").forEach(b=>b.onclick=()=>{$("#subject").value=b.dataset.s;subject=b.dataset.s;info()});
$("#start").onclick=start;$("#heroStart").onclick=()=>$("#practice").scrollIntoView({behavior:"smooth"});$("#next").onclick=next;$("#retry").onclick=start;$("#change").onclick=()=>{$("#result").classList.add("hidden");$("#practice").classList.remove("hidden");$("#practice").scrollIntoView({behavior:"smooth"})};$("#theme").onclick=()=>document.body.classList.toggle("dark");info();dash();